package com.example.dao;

import com.example.entity.AnjvkeDonghu;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface AnjvkeDonghuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anjvke_donghu
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anjvke_donghu
     *
     * @mbggenerated
     */
    int insert(AnjvkeDonghu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anjvke_donghu
     *
     * @mbggenerated
     */
    int insertSelective(AnjvkeDonghu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anjvke_donghu
     *
     * @mbggenerated
     */
    AnjvkeDonghu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anjvke_donghu
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AnjvkeDonghu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anjvke_donghu
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AnjvkeDonghu record);
}