package com.example.entity;

import java.math.BigDecimal;
import java.util.Date;

public class AnjvkeDonghu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anjvke_donghu.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anjvke_donghu.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anjvke_donghu.houseType
     *
     * @mbggenerated
     */
    private String housetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anjvke_donghu.size
     *
     * @mbggenerated
     */
    private Integer size;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anjvke_donghu.height
     *
     * @mbggenerated
     */
    private String height;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anjvke_donghu.buildYear
     *
     * @mbggenerated
     */
    private Date buildyear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anjvke_donghu.totalPrice
     *
     * @mbggenerated
     */
    private BigDecimal totalprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anjvke_donghu.price
     *
     * @mbggenerated
     */
    private Integer price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anjvke_donghu.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anjvke_donghu.heightNumber
     *
     * @mbggenerated
     */
    private Byte heightnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anjvke_donghu.village
     *
     * @mbggenerated
     */
    private String village;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anjvke_donghu.streetName
     *
     * @mbggenerated
     */
    private String streetname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column anjvke_donghu.id
     *
     * @return the value of anjvke_donghu.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column anjvke_donghu.id
     *
     * @param id the value for anjvke_donghu.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column anjvke_donghu.title
     *
     * @return the value of anjvke_donghu.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column anjvke_donghu.title
     *
     * @param title the value for anjvke_donghu.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column anjvke_donghu.houseType
     *
     * @return the value of anjvke_donghu.houseType
     *
     * @mbggenerated
     */
    public String getHousetype() {
        return housetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column anjvke_donghu.houseType
     *
     * @param housetype the value for anjvke_donghu.houseType
     *
     * @mbggenerated
     */
    public void setHousetype(String housetype) {
        this.housetype = housetype == null ? null : housetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column anjvke_donghu.size
     *
     * @return the value of anjvke_donghu.size
     *
     * @mbggenerated
     */
    public Integer getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column anjvke_donghu.size
     *
     * @param size the value for anjvke_donghu.size
     *
     * @mbggenerated
     */
    public void setSize(Integer size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column anjvke_donghu.height
     *
     * @return the value of anjvke_donghu.height
     *
     * @mbggenerated
     */
    public String getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column anjvke_donghu.height
     *
     * @param height the value for anjvke_donghu.height
     *
     * @mbggenerated
     */
    public void setHeight(String height) {
        this.height = height == null ? null : height.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column anjvke_donghu.buildYear
     *
     * @return the value of anjvke_donghu.buildYear
     *
     * @mbggenerated
     */
    public Date getBuildyear() {
        return buildyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column anjvke_donghu.buildYear
     *
     * @param buildyear the value for anjvke_donghu.buildYear
     *
     * @mbggenerated
     */
    public void setBuildyear(Date buildyear) {
        this.buildyear = buildyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column anjvke_donghu.totalPrice
     *
     * @return the value of anjvke_donghu.totalPrice
     *
     * @mbggenerated
     */
    public BigDecimal getTotalprice() {
        return totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column anjvke_donghu.totalPrice
     *
     * @param totalprice the value for anjvke_donghu.totalPrice
     *
     * @mbggenerated
     */
    public void setTotalprice(BigDecimal totalprice) {
        this.totalprice = totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column anjvke_donghu.price
     *
     * @return the value of anjvke_donghu.price
     *
     * @mbggenerated
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column anjvke_donghu.price
     *
     * @param price the value for anjvke_donghu.price
     *
     * @mbggenerated
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column anjvke_donghu.createTime
     *
     * @return the value of anjvke_donghu.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column anjvke_donghu.createTime
     *
     * @param createtime the value for anjvke_donghu.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column anjvke_donghu.heightNumber
     *
     * @return the value of anjvke_donghu.heightNumber
     *
     * @mbggenerated
     */
    public Byte getHeightnumber() {
        return heightnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column anjvke_donghu.heightNumber
     *
     * @param heightnumber the value for anjvke_donghu.heightNumber
     *
     * @mbggenerated
     */
    public void setHeightnumber(Byte heightnumber) {
        this.heightnumber = heightnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column anjvke_donghu.village
     *
     * @return the value of anjvke_donghu.village
     *
     * @mbggenerated
     */
    public String getVillage() {
        return village;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column anjvke_donghu.village
     *
     * @param village the value for anjvke_donghu.village
     *
     * @mbggenerated
     */
    public void setVillage(String village) {
        this.village = village == null ? null : village.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column anjvke_donghu.streetName
     *
     * @return the value of anjvke_donghu.streetName
     *
     * @mbggenerated
     */
    public String getStreetname() {
        return streetname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column anjvke_donghu.streetName
     *
     * @param streetname the value for anjvke_donghu.streetName
     *
     * @mbggenerated
     */
    public void setStreetname(String streetname) {
        this.streetname = streetname == null ? null : streetname.trim();
    }
}